### ISSUE TITLE
RuthAndRoth Group and Region in OSGrid

### ISSUE THREAD

**Issue by aiaustin** [RuthAndRoth/Ruth#16]
We have started a group on OSGrid ** called RuthAndRoth. Feel free to join.

We are also creating a simple group owned region on OSGrid with region name RuthAndRoth. Serie and Ai are at the moment joint owners though we can add more if its useful. Owners have build rights.

We have put the Ruth RC#3 and Roth RC#1 and related items on a shelf unit on the region. The contents are identical to the 2018-12-29 version that is on OSGrid Vue-Port.

The region is currently hosted on one of Aiâ€™s servers at the University of Edinburgh, though the plan is to keep its contents open source licensed and hopefully an OAR can be made and shared.

** OSGrid (http://osgrid.org) is an open free access and test/experimental community grid.

**Comment by AdaRadius** [comment]
That sounds good - a uni gives some cover for license issues as well.

Osgrid is run under US 501(c)(3) nonprofit registered in Georgia, and not registered in enough US states to do online fundraising legally. I'm not sure when or if that's going to catch up with them. 

[I am a retired CPA]

New Media Arts is a California 501(c)(3) nonprofit that is registered in the 30-ish states required to do online fundraising, and whose mission is libraries and edu. Their servers are in Canada and the Netherlands. I'm asking their tech director and library director if hosting a small grid on one of its servers would be viable for hosting some Ruth & Ruth boxes. Our VR presence is mostly in Kitely grid now, including Community Virtual Library, and a one-sim library for Arcadis Arylum/Aley exports from SL (picking up the pieces from when Virtual Christine had to close most of her sims). But some licensing issues would be easier to deal with in our own grid.  We'll see. 

A couple of distribution points owned by different flavors of nonprofits in several countries should bring this project some sustainability.  I am delighted that you're thinking of this too :)

**Comment by aiaustin** [comment]
Excellent Ada. We can always make an OAR of any content we build and upload it back on any region on any (open) grid. Lets keep ALL CONTENT on our region(s) open source and free to allow it to be copied and hosted elsewhere.

My OSGrid add-on regions server is reasonably stable, it is just a Windows 10 Pro desktop and managed personally by me, so is prone to the silly Windows update reboot issues if I am unavailable.

**Comment by aiaustin** [comment]
A bit of layout done on the region.. which is intended just for experiments for now.  Then we can do a tidy up after we have settled down what is useful. The idea is that all the stuff on this region will be full perm and that we can take an OAR to put in the GitHub repository act as an archive and backup should personnel, servers or grid choice need to change.

hop://login.osgrid.org/RuthAndRoth/128/128/26

We now have a central area with a little meeting area, where you will be joined by an example Ruth 2.0 and Roth 2.0 NPC.  Then 4 close by platforms for content, 4 further away "outrigger" areas at N, S, E and W. The corners are left open so sky platforms for creators can be placed (above 1,000m so they don't show on the map tile by default) where that is useful.

![2018-09-12-OSGrid-OSGrid_001](https://user-images.githubusercontent.com/4630885/55475098-e00b2800-560a-11e9-9d3f-0adfe2208dc4.jpg)

**Comment by AdaRadius** [comment]
I'm on my way over there.

**Comment by AdaRadius** [comment]
The island looks perfect - simple and easy to understand and navigate. Even for me :)  I've joined the group and sent friends request. Would it be possible for me to rez here so that I can rez bodies? RuthRC#4 is ready for inworld testing of the vertex weighting, and I'm starting on alpha cut design.

**Comment by aiaustin** [comment]
Sure Ada,  I have given you role “creator” and if you set the group active you can now rez on the region. I am not sure how qell broups and roles work across Hypergrid. but try and let me know if there are issues.

Try to keep anything you put on the region full perm to all levels so we can make a clean OAR of the contents.

Region is still experimental. We may have an area per creator... like the Gitzhub contrib/name directory idea or something like that... and meep an area separate for the agreed joint release, so that is always clear. For now use an empty rack if you wish. Take a copy of the rack to rez a new one anytime.

Friend requests to offline avatars do seem to be a problem over the Hypergrid. I did not see the request when I logged in. But we can link up if we are online together sometime.

**Comment by AdaRadius** [comment]
Thank you! The area near the landing point for current distribution, and maybe set up a testing area on on another pier? - a bunch of pose stands loaded with sits, runs, etc. should do it. I can bring them over from my inventory. We could put out no-modify/no transfer/yes copy body parts clearly marked "IT'S A DRAFT" for people to pick up for testing - we won't care if those don't get picked up by the OARs as we're stashing all drafts at GitHub.  I'll see if I have time today to bring in the pose stands and upload the last draft - I need to sort through my animations to filter out the ones that aren't full perm/open source.

**Comment by aiaustin** [comment]
Sounds good. Choose your own quadrant platform Ada.

I checked a HG group member set as creator, and they are able to build something so long  as RuthAndRoth group is activated.

**Comment by AdaRadius** [comment]
I took a dock, brought in pose stands and animations, and it's working well. Thank you!

**Comment by aiaustin** [comment]
Great... there are some lights along the way now too... safety first!
![2019-04-08-OSGrid-RuthAndRoth-Lighting](https://user-images.githubusercontent.com/4630885/55736129-9f504c00-5a1a-11e9-8e6a-46e4c0ac1b32.jpg)

**Comment by AdaRadius** [comment]
oo shiny :)

**Comment by aiaustin** [comment]
Issue Closed.
