### ISSUE TITLE
Mesh parts stretched to 0,0,0

### ISSUE THREAD

**Issue by aiaustin** [RuthAndRoth/Ruth#20]
I am not sure if this is an issue or not... but will post a couple of screen shots in case someone recognizes this as a potential R2 parts mesh issue.  I was testing some mesh rich regions in CtrlAltStudio viewer 1.2.6-43412 as the last Oculus Rift VR viewer we still can use with OpenSim. Note that this release is based on Firestorm 4.6.9 with hotfix 42974  which were released in December 2014.  Most things still work well.  BUT... I noticed an issue with a Ruth 2.0 and a Roth 2.0 NPC (and it is the same for normal avatars).  Each hand and the head of Ruth and Roth have stretched mesh that goes from its attachment position to 0,0,0 on the region.
![Snapshot_001](https://user-images.githubusercontent.com/4630885/55684596-9bea9100-5944-11e9-9c26-9a1251acb40c.png)
I wonder if this is something that we have to live with in older viewers.. or if anyone can think why just these mesh parts would be problematic while most parts (feet, body, etc) work fine?
![2019-04-07-OSGrid-R2-Mesh-to-000-1](https://user-images.githubusercontent.com/4630885/55684612-e3711d00-5944-11e9-9c1d-bfc2bdf280a2.png)
![2019-04-07-OSGrid-R2-Mesh-to-000-2](https://user-images.githubusercontent.com/4630885/55684613-e9ff9480-5944-11e9-8d69-021d0d2ddf44.png)

**Comment by AdaRadius** [comment]
It's a viewer issue, AFAIK; it's been a few years since I've seen it.

**Comment by aiaustin** [comment]
I agree its an older viewer.  CtrlAltStudio (last version CtrlAltStudio 1.2.6.43412) is based on Firestorm 4.6.9 with hotfix 42974  which were released in December 2014.

I just wondered what it was about the specific parts that caused this issue in case it could be removed.  Most parts and the core body, feet, etc are fine.  Just each hand and the head (male and female) seem to do this.

**Comment by Fritigern** [comment]
Ai, Ada, this is a viewer issue alright. This is what happens when a non-Bento capable viewer tries to display bento attachments.
Simply use a Bento-capable viewer to view the attachments the way they should be seen.

**Comment by aiaustin** [comment]
Ah, got it Fritigern...CtrlAltStudio is definitely pre-Bento. Wonder why its just the hands and heads though.. even when hands are on one piece body like Sean’s RothToo... and not for example the feet.

**Comment by Fritigern** [comment]
Because the hands and face received new bones when Bento got introduced. The hands got new bones to articulate the fingers, the face got new bones to animate the face, but the feet got nothing.  The body got new bones too, but Ruth/Roth does not use them because those are usually used for extra legs, wings, tail, etc.
This is why the body and the feet do not stretch to infinity in non-Bento viewers.

Note that had you been wearing a bento tail, wings, or anything of the like, those would have been stretched to infinity as well.

**Comment by aiaustin** [comment]
Excellent and full explanation. Many thanks. Good to know this level of detail.

**Comment by aiaustin** [comment]
Issue closed.
