### ISSUE TITLE
Ruth 2.0 RC3 Does not work well with ground-sit

### ISSUE THREAD

**Issue by zauberparacelsus** [RuthAndRoth/Ruth#5]
When using the Ruth 2.0 avatar, the upper part of the thighs do not deform very well when sitting on the ground.

![snapshot](https://i.gyazo.com/76e156beebb2dd580a54ee4ceaf5a3fb.png)

**Comment by seriesumei** [comment]
Right now there are a number of versions of the mesh floating around, I hope soon we can agree on a specific version to use for a common base and re-test this and see if it is still a problem.  Do you know which blend or DAE file this is in the image?

**Comment by zauberparacelsus** [comment]
Whatever version Myra Foil had uploaded to the Islandz grid before it closed.  Though I've noticed a problem in general with "rubber hosing" on some of the joints, where they just collapse inward when bent (much like the snapshot above)

**Comment by seriesumei** [comment]
Thanks.  Ada is pulling together what will likely be the base for RC4, once she gets that together we can see where things stand.

**Comment by zauberparacelsus** [comment]
If you are in contact with Ada can you pass along some additional observations that were made by a friend of mine?
* When manipulated with the sliders, the inner corners of the eyes cannot go down, they only go up, so you cannot get almond-shaped eyes.
* If the shoulders were an inch higher, and if the butt were a little smaller, the Ruth body would have an easier time fitting with more of the pre-existing mesh clothes.

If you or Ada want to contact my friend more directly for details, she is Raven Callisto at the Tag Grid.

**Comment by AdaRadius** [comment]
Hi! The inworld sliders for the face are controlled by shape keys, rather than the armature, and in SL/OpenSim they can only be used with the default headMesh. Bottom line, nothing I can do about the eye sliders. 
Ya, true about existing mesh clothes, many of which are based on the SL/OS default avatar. I think Shin Ingen (who did the modeling of this body) preferred to take the high road and make a more natural and  better looking model. I am rigging it so that it responds as well as possible to the sliders, so you can flatten the butt if you want to, though the shoulders will still be lower. Fitted mesh clothing will work better than the fives sizes mesh models. If we manage to get the alpha cuts organized better, we should be able to accommodate more, if not all, existing mesh clothing.  
Ya, I'm working on the sits and noodle limbs. I agree, not good enough yet.

**Comment by zauberparacelsus** [comment]
Hi Ada, thank you for the reply.

Are you sure about the thing with the head mesh?  The bento skeleton adds roughly 30 bones to the face to allow head meshes to be controlled with the sliders.

**Comment by aiaustin** [comment]
Ada, I was able to make the eye openings larger and rounder and extend the chin a bit in a shape using the bento head included with Ruth RC#n. I did use a bento compatible starter shape like one included in the release packages. The non-bento shapes I had for the normal avatars did not translate well to Ruth 2.0.

**Comment by AdaRadius** [comment]
Ouch I certainly could be out of date on Bento heads - I think it was late 2017 when a few of use were looking at it for Ruth. At that point it was less frustrating to use the default head. And still might be - do you know if altering the shape keys is allowed inworld or are we stuck with the default shape keys?  If I can, I'll take a look at it after we have the two bodies done and tested.

**Comment by zauberparacelsus** [comment]
With the bento skeleton, I don't think shape keys are used at all, everything is bone-driven.  As I mentioned before though, the bento skeleton adds about 30 bonus to the head, many of which are hooked up to shape sliders.

**Comment by aiaustin** [comment]
I think so long as we start with a bento shape that works the adjusters do pretty much what you expect. In all my tests on Ruth 2.0 and Ruth 2.0 I have had full alpha and used the included Bento Head and my (relatively minor) adjustments have all been fine Ada.

**Comment by zauberparacelsus** [comment]
![bento head](http://blog.machinimatrix.org/wp-content/uploads/2012/07/reference-073.png)

**Comment by AdaRadius** [comment]
I just loaded one into Blender with the Avastar plugin - there are vertex groups for the bones plus shape keys. And rats, eyelid_corner_up_20650 and eyelid_inner_corner_up are controlled by the shape keys, not the bones, and only go up, not down, as you said. It looks like they took the old head and just added the bento bones on top of the old topography. Gack. Avastar says if I mess with the topography the sliders may not work inworld, which is what I remember from the last time I tried to work with this. Very disappointing.

**Comment by zauberparacelsus** [comment]
Perhaps the Avastar head is rigged incorrectly?  With the head of that avatar in the snapshot of the original post, the eye corners *do* go up and down, so it *should* be possible.

**Comment by zauberparacelsus** [comment]
Actually, what version of Avastar are you using?  I just tested with the latest version (2.5-1), and the eye corners move up and down correctly... though there is a bug where the head shrinks if you change any of the shape sliders.  I will be reporting that to Gaia right away.

EDIT: ...and she's closed the bug tracker while she works on getting Avastar ported to Blender 2.80

EDIT 2: Okay, it only occurs if you enter edit mode with the head selected, even if you don't make any changes or select any geometry.  So, all working fine, so long as you don't go into edit mode with the avastar head

**Comment by AdaRadius** [comment]
Avastar v2.5.18

**Comment by zauberparacelsus** [comment]
Okay, I'll report that to Gaia on the Avastar Discord server

**Comment by zauberparacelsus** [comment]
@AdaRadius Etheria Parrot recommends trying the latest daily build (2.5-33), and says that the inner eye sliders are working without issue on it.

**Comment by aiaustin** [comment]
If we are preparing materials that could become the basis for a Ruth RC#4 can I suggest we start a new issue to input matters relating to that that are beyond the shape/sliders/head issue being discussed here?  I will kick one off now.

**Comment by aiaustin** [comment]
I believe this as been mentioned before but worth noting again.. while setting up a seated Roth 2.0 RC#1 NPC I see that the lower back of Roth does not look right...

![Roth-2 0-RC1-Back-Problem](https://user-images.githubusercontent.com/4630885/55318429-abf90100-546a-11e9-94d6-90ca54f680c3.jpg)

**Comment by zauberparacelsus** [comment]
Yep, rubber hosing

**Comment by aiaustin** [comment]
As well as the lower back shape, the thighs on Roth 2.0 RC#1 are quite angled when Roth is seated...
![Roth-RC1-Thighs-and-Lower-Back](https://user-images.githubusercontent.com/4630885/55863592-c28e0f00-5b72-11e9-978c-5018345cce3b.jpg)

**Comment by AdaRadius** [comment]
Ya, Roth is a mess. I'm hoping to get to him in a few days, but I've said that several few days ago. Soon. Before Blender2.8 comes out, anyway.

**Comment by seriesumei** [comment]
I am closing this as Ada is doing major re-work to Roth and ultimately both armatures.  We can talk about what comes out of that in new issues as required.
